### PR TITLE
I've made a substantial performance improvement and the server info command now displays the info using the standard embed

### PR DESCRIPTION
**Pull request by LakshyaShastri**
Also, I've renamed the `Bot_prefix` variable to `BOT_PREFIX` as per [PEP8](https://www.python.org/dev/peps/pep-0008)

### CODE REVIEW

**Comment by LakshyaShastri** [comment]
can you look into this error?

**Comment by LakshyaShastri** [comment]
Hmmm this is weird, all the files are black formatted and follow flake8 linting but the checks still don't pass, could you look into this? It says that it would reformat `main.py` 
image but the file is already formatted 
image

**Comment by RDIL** [comment]
Hey @LakshyaShastri,
Thank you so much for the pull request!

The check was failing because you didn't run `make format`, but I have done that and now it should pass.  

Thanks again!

**Comment by LakshyaShastri** [comment]
Brilliant!

**Comment by RDIL** [comment]
I'm going to test this out on my machine later and if it works I'll merge it.

**Comment by LakshyaShastri** [comment]
Aight

**Review by RDIL — APPROVED** [review]

**Pull request merged**
